/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.ombcrew.taskManagementSample.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the TaskManagementSample service. Represents a row in the &quot;OMBTFA_TaskManagementSample&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.ombcrew.taskManagementSample.model.impl.TaskManagementSampleModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.ombcrew.taskManagementSample.model.impl.TaskManagementSampleImpl</code>.
 * </p>
 *
 * @author OMB
 * @see TaskManagementSample
 * @generated
 */
@ProviderType
public interface TaskManagementSampleModel
	extends BaseModel<TaskManagementSample> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a Task Management Sample model instance should use the {@link TaskManagementSample} interface instead.
	 */

	/**
	 * Returns the primary key of this Task Management Sample.
	 *
	 * @return the primary key of this Task Management Sample
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this Task Management Sample.
	 *
	 * @param primaryKey the primary key of this Task Management Sample
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the task ID of this Task Management Sample.
	 *
	 * @return the task ID of this Task Management Sample
	 */
	public long getTaskId();

	/**
	 * Sets the task ID of this Task Management Sample.
	 *
	 * @param taskId the task ID of this Task Management Sample
	 */
	public void setTaskId(long taskId);

	/**
	 * Returns the group ID of this Task Management Sample.
	 *
	 * @return the group ID of this Task Management Sample
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this Task Management Sample.
	 *
	 * @param groupId the group ID of this Task Management Sample
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the created user ID of this Task Management Sample.
	 *
	 * @return the created user ID of this Task Management Sample
	 */
	public long getCreatedUserId();

	/**
	 * Sets the created user ID of this Task Management Sample.
	 *
	 * @param createdUserId the created user ID of this Task Management Sample
	 */
	public void setCreatedUserId(long createdUserId);

	/**
	 * Returns the created user uuid of this Task Management Sample.
	 *
	 * @return the created user uuid of this Task Management Sample
	 */
	public String getCreatedUserUuid();

	/**
	 * Sets the created user uuid of this Task Management Sample.
	 *
	 * @param createdUserUuid the created user uuid of this Task Management Sample
	 */
	public void setCreatedUserUuid(String createdUserUuid);

	/**
	 * Returns the created date of this Task Management Sample.
	 *
	 * @return the created date of this Task Management Sample
	 */
	public Date getCreatedDate();

	/**
	 * Sets the created date of this Task Management Sample.
	 *
	 * @param createdDate the created date of this Task Management Sample
	 */
	public void setCreatedDate(Date createdDate);

	/**
	 * Returns the title of this Task Management Sample.
	 *
	 * @return the title of this Task Management Sample
	 */
	@AutoEscape
	public String getTitle();

	/**
	 * Sets the title of this Task Management Sample.
	 *
	 * @param title  the title of this Task Management Sample
	 */
	public void setTitle(String title);

	/**
	 * Returns the description of this Task Management Sample.
	 *
	 * @return the description of this Task Management Sample
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this Task Management Sample.
	 *
	 * @param description the description of this Task Management Sample
	 */
	public void setDescription(String description);

	/**
	 * Returns the assigned user ID of this Task Management Sample.
	 *
	 * @return the assigned user ID of this Task Management Sample
	 */
	public long getAssignedUserId();

	/**
	 * Sets the assigned user ID of this Task Management Sample.
	 *
	 * @param assignedUserId the assigned user ID of this Task Management Sample
	 */
	public void setAssignedUserId(long assignedUserId);

	/**
	 * Returns the assigned user uuid of this Task Management Sample.
	 *
	 * @return the assigned user uuid of this Task Management Sample
	 */
	public String getAssignedUserUuid();

	/**
	 * Sets the assigned user uuid of this Task Management Sample.
	 *
	 * @param assignedUserUuid the assigned user uuid of this Task Management Sample
	 */
	public void setAssignedUserUuid(String assignedUserUuid);

}