/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.ombcrew.taskManagementSample.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;

import com.ombcrew.taskManagementSample.model.TaskManagementSample;
import com.ombcrew.taskManagementSample.model.TaskManagementSampleModel;
import com.ombcrew.taskManagementSample.model.TaskManagementSampleSoap;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the TaskManagementSample service. Represents a row in the &quot;OMBTFA_TaskManagementSample&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>TaskManagementSampleModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link TaskManagementSampleImpl}.
 * </p>
 *
 * @author OMB
 * @see TaskManagementSampleImpl
 * @generated
 */
@JSON(strict = true)
public class TaskManagementSampleModelImpl
	extends BaseModelImpl<TaskManagementSample>
	implements TaskManagementSampleModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a Task Management Sample model instance should use the <code>TaskManagementSample</code> interface instead.
	 */
	public static final String TABLE_NAME = "OMBTFA_TaskManagementSample";

	public static final Object[][] TABLE_COLUMNS = {
		{"taskId", Types.BIGINT}, {"groupId", Types.BIGINT},
		{"createdUserId", Types.BIGINT}, {"createdDate", Types.TIMESTAMP},
		{"title", Types.VARCHAR}, {"description", Types.VARCHAR},
		{"assignedUserId", Types.BIGINT}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("taskId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("createdUserId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("createdDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("title", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("description", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("assignedUserId", Types.BIGINT);
	}

	public static final String TABLE_SQL_CREATE =
		"create table OMBTFA_TaskManagementSample (taskId LONG not null primary key,groupId LONG,createdUserId LONG,createdDate DATE null,title VARCHAR(75) null,description VARCHAR(75) null,assignedUserId LONG)";

	public static final String TABLE_SQL_DROP =
		"drop table OMBTFA_TaskManagementSample";

	public static final String ORDER_BY_JPQL =
		" ORDER BY taskManagementSample.taskId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY OMBTFA_TaskManagementSample.taskId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	public static final long GROUPID_COLUMN_BITMASK = 1L;

	public static final long TITLE_COLUMN_BITMASK = 2L;

	public static final long TASKID_COLUMN_BITMASK = 4L;

	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
		_entityCacheEnabled = entityCacheEnabled;
	}

	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
		_finderCacheEnabled = finderCacheEnabled;
	}

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static TaskManagementSample toModel(
		TaskManagementSampleSoap soapModel) {

		if (soapModel == null) {
			return null;
		}

		TaskManagementSample model = new TaskManagementSampleImpl();

		model.setTaskId(soapModel.getTaskId());
		model.setGroupId(soapModel.getGroupId());
		model.setCreatedUserId(soapModel.getCreatedUserId());
		model.setCreatedDate(soapModel.getCreatedDate());
		model.setTitle(soapModel.getTitle());
		model.setDescription(soapModel.getDescription());
		model.setAssignedUserId(soapModel.getAssignedUserId());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<TaskManagementSample> toModels(
		TaskManagementSampleSoap[] soapModels) {

		if (soapModels == null) {
			return null;
		}

		List<TaskManagementSample> models = new ArrayList<TaskManagementSample>(
			soapModels.length);

		for (TaskManagementSampleSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public TaskManagementSampleModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _taskId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setTaskId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _taskId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return TaskManagementSample.class;
	}

	@Override
	public String getModelClassName() {
		return TaskManagementSample.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<TaskManagementSample, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<TaskManagementSample, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<TaskManagementSample, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((TaskManagementSample)this));
		}

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<TaskManagementSample, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<TaskManagementSample, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(TaskManagementSample)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<TaskManagementSample, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<TaskManagementSample, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, TaskManagementSample>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			TaskManagementSample.class.getClassLoader(),
			TaskManagementSample.class, ModelWrapper.class);

		try {
			Constructor<TaskManagementSample> constructor =
				(Constructor<TaskManagementSample>)proxyClass.getConstructor(
					InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException
							reflectiveOperationException) {

					throw new InternalError(reflectiveOperationException);
				}
			};
		}
		catch (NoSuchMethodException noSuchMethodException) {
			throw new InternalError(noSuchMethodException);
		}
	}

	private static final Map<String, Function<TaskManagementSample, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<TaskManagementSample, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<TaskManagementSample, Object>>
			attributeGetterFunctions =
				new LinkedHashMap
					<String, Function<TaskManagementSample, Object>>();
		Map<String, BiConsumer<TaskManagementSample, ?>>
			attributeSetterBiConsumers =
				new LinkedHashMap
					<String, BiConsumer<TaskManagementSample, ?>>();

		attributeGetterFunctions.put("taskId", TaskManagementSample::getTaskId);
		attributeSetterBiConsumers.put(
			"taskId",
			(BiConsumer<TaskManagementSample, Long>)
				TaskManagementSample::setTaskId);
		attributeGetterFunctions.put(
			"groupId", TaskManagementSample::getGroupId);
		attributeSetterBiConsumers.put(
			"groupId",
			(BiConsumer<TaskManagementSample, Long>)
				TaskManagementSample::setGroupId);
		attributeGetterFunctions.put(
			"createdUserId", TaskManagementSample::getCreatedUserId);
		attributeSetterBiConsumers.put(
			"createdUserId",
			(BiConsumer<TaskManagementSample, Long>)
				TaskManagementSample::setCreatedUserId);
		attributeGetterFunctions.put(
			"createdDate", TaskManagementSample::getCreatedDate);
		attributeSetterBiConsumers.put(
			"createdDate",
			(BiConsumer<TaskManagementSample, Date>)
				TaskManagementSample::setCreatedDate);
		attributeGetterFunctions.put("title", TaskManagementSample::getTitle);
		attributeSetterBiConsumers.put(
			"title",
			(BiConsumer<TaskManagementSample, String>)
				TaskManagementSample::setTitle);
		attributeGetterFunctions.put(
			"description", TaskManagementSample::getDescription);
		attributeSetterBiConsumers.put(
			"description",
			(BiConsumer<TaskManagementSample, String>)
				TaskManagementSample::setDescription);
		attributeGetterFunctions.put(
			"assignedUserId", TaskManagementSample::getAssignedUserId);
		attributeSetterBiConsumers.put(
			"assignedUserId",
			(BiConsumer<TaskManagementSample, Long>)
				TaskManagementSample::setAssignedUserId);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public long getTaskId() {
		return _taskId;
	}

	@Override
	public void setTaskId(long taskId) {
		_columnBitmask = -1L;

		_taskId = taskId;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_columnBitmask |= GROUPID_COLUMN_BITMASK;

		if (!_setOriginalGroupId) {
			_setOriginalGroupId = true;

			_originalGroupId = _groupId;
		}

		_groupId = groupId;
	}

	public long getOriginalGroupId() {
		return _originalGroupId;
	}

	@JSON
	@Override
	public long getCreatedUserId() {
		return _createdUserId;
	}

	@Override
	public void setCreatedUserId(long createdUserId) {
		_createdUserId = createdUserId;
	}

	@Override
	public String getCreatedUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getCreatedUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setCreatedUserUuid(String createdUserUuid) {
	}

	@JSON
	@Override
	public Date getCreatedDate() {
		return _createdDate;
	}

	@Override
	public void setCreatedDate(Date createdDate) {
		_createdDate = createdDate;
	}

	@JSON
	@Override
	public String getTitle() {
		if (_title == null) {
			return "";
		}
		else {
			return _title;
		}
	}

	@Override
	public void setTitle(String title) {
		_columnBitmask |= TITLE_COLUMN_BITMASK;

		if (_originalTitle == null) {
			_originalTitle = _title;
		}

		_title = title;
	}

	public String getOriginalTitle() {
		return GetterUtil.getString(_originalTitle);
	}

	@JSON
	@Override
	public String getDescription() {
		if (_description == null) {
			return "";
		}
		else {
			return _description;
		}
	}

	@Override
	public void setDescription(String description) {
		_description = description;
	}

	@JSON
	@Override
	public long getAssignedUserId() {
		return _assignedUserId;
	}

	@Override
	public void setAssignedUserId(long assignedUserId) {
		_assignedUserId = assignedUserId;
	}

	@Override
	public String getAssignedUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getAssignedUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setAssignedUserUuid(String assignedUserUuid) {
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			0, TaskManagementSample.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public TaskManagementSample toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, TaskManagementSample>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		TaskManagementSampleImpl taskManagementSampleImpl =
			new TaskManagementSampleImpl();

		taskManagementSampleImpl.setTaskId(getTaskId());
		taskManagementSampleImpl.setGroupId(getGroupId());
		taskManagementSampleImpl.setCreatedUserId(getCreatedUserId());
		taskManagementSampleImpl.setCreatedDate(getCreatedDate());
		taskManagementSampleImpl.setTitle(getTitle());
		taskManagementSampleImpl.setDescription(getDescription());
		taskManagementSampleImpl.setAssignedUserId(getAssignedUserId());

		taskManagementSampleImpl.resetOriginalValues();

		return taskManagementSampleImpl;
	}

	@Override
	public int compareTo(TaskManagementSample taskManagementSample) {
		int value = 0;

		if (getTaskId() < taskManagementSample.getTaskId()) {
			value = -1;
		}
		else if (getTaskId() > taskManagementSample.getTaskId()) {
			value = 1;
		}
		else {
			value = 0;
		}

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof TaskManagementSample)) {
			return false;
		}

		TaskManagementSample taskManagementSample = (TaskManagementSample)obj;

		long primaryKey = taskManagementSample.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return _entityCacheEnabled;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return _finderCacheEnabled;
	}

	@Override
	public void resetOriginalValues() {
		TaskManagementSampleModelImpl taskManagementSampleModelImpl = this;

		taskManagementSampleModelImpl._originalGroupId =
			taskManagementSampleModelImpl._groupId;

		taskManagementSampleModelImpl._setOriginalGroupId = false;

		taskManagementSampleModelImpl._originalTitle =
			taskManagementSampleModelImpl._title;

		taskManagementSampleModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<TaskManagementSample> toCacheModel() {
		TaskManagementSampleCacheModel taskManagementSampleCacheModel =
			new TaskManagementSampleCacheModel();

		taskManagementSampleCacheModel.taskId = getTaskId();

		taskManagementSampleCacheModel.groupId = getGroupId();

		taskManagementSampleCacheModel.createdUserId = getCreatedUserId();

		Date createdDate = getCreatedDate();

		if (createdDate != null) {
			taskManagementSampleCacheModel.createdDate = createdDate.getTime();
		}
		else {
			taskManagementSampleCacheModel.createdDate = Long.MIN_VALUE;
		}

		taskManagementSampleCacheModel.title = getTitle();

		String title = taskManagementSampleCacheModel.title;

		if ((title != null) && (title.length() == 0)) {
			taskManagementSampleCacheModel.title = null;
		}

		taskManagementSampleCacheModel.description = getDescription();

		String description = taskManagementSampleCacheModel.description;

		if ((description != null) && (description.length() == 0)) {
			taskManagementSampleCacheModel.description = null;
		}

		taskManagementSampleCacheModel.assignedUserId = getAssignedUserId();

		return taskManagementSampleCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<TaskManagementSample, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			4 * attributeGetterFunctions.size() + 2);

		sb.append("{");

		for (Map.Entry<String, Function<TaskManagementSample, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<TaskManagementSample, Object> attributeGetterFunction =
				entry.getValue();

			sb.append(attributeName);
			sb.append("=");
			sb.append(
				attributeGetterFunction.apply((TaskManagementSample)this));
			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<TaskManagementSample, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			5 * attributeGetterFunctions.size() + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<TaskManagementSample, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<TaskManagementSample, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(
				attributeGetterFunction.apply((TaskManagementSample)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, TaskManagementSample>
			_escapedModelProxyProviderFunction = _getProxyProviderFunction();

	}

	private static boolean _entityCacheEnabled;
	private static boolean _finderCacheEnabled;

	private long _taskId;
	private long _groupId;
	private long _originalGroupId;
	private boolean _setOriginalGroupId;
	private long _createdUserId;
	private Date _createdDate;
	private String _title;
	private String _originalTitle;
	private String _description;
	private long _assignedUserId;
	private long _columnBitmask;
	private TaskManagementSample _escapedModel;

}